name: nplugins
version: 1.0.
author: Vish
main: com.vs.nplugins.nplugins
commands:
  heal:
    description: Heal player max
    usage: /<command>
    aliases: /healmanya

  feed:
    description: Feed player to max saturation
    usage: /<command>
    aliases: /feedmanya

  farmtime:
    description: spawns a specified farm animal
    usage: /<command>
    aliases: /farmtimemanya
